name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dev dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: sync --dev
    - name: run unit tests
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: pytest
